audit_header: false
title: San Antonio Real Estate Video Blog with Patrick Hammonds
description: Our mission at The Hammonds Group is to be your best resource for San Antonio real estate advice. Whether you are a buyer, seller, or investor, our team of professionals can answer any questions you might have about real estate. If you are looking to buy or sell a home, you can get all the information and the latest updates, tips, and tricks from The The Hammonds Group, your professional San Antonio Real Estate Agents.
show_custom_links: false
custom_links:
  - title:
    url:
show_custom_links_new_tab: false
custom_links_new_tab:
  - title:
    url:

client:
  name: Patrick Hammonds
  title:
  license_number:
  about_markdown: |
    I have lived in San Antonio most of my life, and love this city. We are culturally diverse, and keeping up with all the coolest nationwide trends! After a long history in Sales, I chose to get my Real Estate License and help people instead of selling people. 5 years in the business has taken me to all sides of our city, and lots of families helped. Whether you are looking to sell or buy, I can assist you in the best way possible, and help you find not on the best home for you, but the best area based on your lifestyle. I love my Career!
  brand: The Hammonds Group
  brokerage: Keller Williams Heritage
  market: San Antonio
  address: '2338 N Loop 1604W #120, San Antonio, Texas 78248'
  phone: 210-319-0569
  phone_type:
  phone2:
  phone2_type:
  email: patrick@thehammondsgroupkw.com
  url: https://phammonds.kw.com

CTAs:
  first_CTA_text: Home Valuation
  first_CTA_URL: /homevalue/
  second_CTA_text: Home Search
  second_CTA_URL: /homesearch/

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.jpg
    CTA_title: "What’s Your San Antonio Home Worth?"
    CTA_text: "Are you thinking of selling your home or interested in learning about home prices in your neighborhood? We can help you."
    CTA_link_text: "Free Home Value Report"
    CTA_url: /homevalue/

second_sidebar_CTA:
  - CTA_image_path2: /img/cta-images/002.jpg
    CTA_title2: "Looking for a San Antonio Home?"
    CTA_text2: "Search the entire MLS for your San Antonio home."
    CTA_link_text2: "Search the MLS"
    CTA_url2: /homesearch/

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: /img/lender-headshot.jpg
  logo_path: /img/lender-logo.png
  name:
  license_number:
  company:
  company_license_number:
  phone:
  email:
  url:

socials:
  review_sm_icons: true
  facebook_url: https://www.facebook.com/TheHammondsGroupKW
  linkedin_url: https://www.linkedin.com/in/patrick-hammonds-realtor-904647a1/
  youtube_url:
  twitter_url: https://twitter.com/hammonds210
  instagram_url:
  pinterest_url:
  zillow_url: https://www.zillow.com/profile/TheHammondsGroup/
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: 'San Antonio Real Estate Podcast with Patrick Hammonds'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the San Antonio Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from The Hammonds Group - your professional San Antonio Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in San Antonio, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: 'Patrick Hammonds'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 30
  hero_text: San Antonio Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
  post_cta_image: /img/home-value.jpg
  post_cta_image2: /img/home-search.jpg

site_colors:
  brand_color: '#b40101'
  theme_color: '#999'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: white

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#b40101'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
